//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowFactory.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryList
    {
        public int Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Salary { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
